### PR TITLE
Use phin instead of got

### PR DESCRIPTION
**Pull request by Ethanent**
[phin](https://github.com/Ethanent/phin) is a fast, lightweight HTTP request library with 0 dependencies. got is still of considerable size with a [dependency tree](http://npm.anvaka.com/#/view/2d/got) size of 21 packages.

In my trials, using phin in place of got improved install time by about 4 seconds and improved overall performance in package-json!

### CODE REVIEW

**Comment by kevva** [comment]
I doubt we're going to change it since `got` is maintained by @sindresorhus. The relatively small improvement to the install time doesn't warrant it either.

**Comment by sindresorhus** [comment]
> phin is a fast

I don't see any benchmarks, so I'm gonna assume it's just meaningless marketing talk.

> library with 0 dependencies

When I read "0 dependencies," it says to me "I reinvented the wheel without understanding the complexities of what I'm creating". I don't mean that as discouragement. I'm talking from experience. Got was also once just 1 file with no dependencies: https://github.com/sindresorhus/got/blob/f9436f5e5863d39f180032687447d9dbe7721dbb/index.js Then the real world kicked in. HTTP is super complex. ;)

**Comment by sindresorhus** [comment]
Not that much difference with npm@5 either:

```
+ got@7.1.0
added 21 packages in 4.372s

+ phin@2.2.5
added 1 package in 2.822s
```

**Comment by Ethanent** [comment]
The main difference, then, is in storage size. phin supports all of the features necessary for package-json (everything got is currently used for in the package) and it's noticeably smaller. phin is just 41KB in size while got and its dependencies are 582KB in size. (~93% reduction in dependency tree size with phin)

**Pull request closed without merging**
