### PR TITLE
Fix types

### LINKED ISSUE #62: `AbbreviatedMetadata` type is incorrect
## To reproduce

```
const metadata: AbbreviatedMetadata = await packageJson('react')
metadata.versions // actually undefined, but has type Readonly<Record<string, AbbreviatedVersion>>
metadata.version // actually a string, but has type unknown
```

It seems strange that the types are broken out-of-the-box. Am I doing something wrong here?

### PR DESCRIPTION
**Pull request by tommy-mitchell**
Fixes #62.

I've gone through https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md and updated the registry types to match (though it seems a little outdated, see https://docs.npmjs.com/about-registry-signatures or https://github.com/npm/registry/pull/24). I've also updated the return type of `packageJson` to match the options provided.

~Type tests are failing due to a `tsd` issue, need to make a PR to add an error code.~

### CODE REVIEW

**Comment by tommy-mitchell** [comment]
Did some manual testing of outputs and added a few more undocumented fields. Think this is good for review.

Not sure what's up with the failing CI, I can't reproduce the errors locally.

**Comment by tommy-mitchell** [comment]
Think I figured it out - `packageJson({fullMetadata: false})` returns `FullVersion`, which has `[key: string]: unknown`:

image

**Comment by tommy-mitchell** [comment]
Another missing `tsd` code:

> Found an error that tsd does not currently support (ts18046)

I didn't even realize they went that high.

**Comment by tommy-mitchell** [comment]
Tests are passing now!

**Comment by tommy-mitchell** [comment]
@sindresorhus this was my last PR :)

**Review by nnfhhvbb — APPROVED** [review]

**Pull request merged**
